"""이사 관련 민원 서비스 Mock 데이터베이스"""

SERVICES_DB: dict[str, dict] = {
    "SVC001": {
        "service_id": "SVC001",
        "service_name": "전입신고",
        "route": "gov24",
        "main_url": "https://www.gov.kr/portal/service/serviceInfo/PTR000050007",
        "legal_basis": ["주민등록법 제11조"],
        "required_documents": ["신분증(주민등록증, 운전면허증 등)"],
        "application_channel": ["online", "mobile", "visit"],
        "contact": "주민센터 (읍·면·동 행정복지센터)",
        "target_region": "all",
        "tags": ["이사", "주소변경", "필수", "전입"],
        "eligibility_summary": "이사한 날로부터 14일 이내에 신고해야 합니다.",
        "processing_days": "즉시",
        "fee": "무료",
    },
    "SVC002": {
        "service_id": "SVC002",
        "service_name": "건강보험 주소 변경",
        "route": "gov24",
        "main_url": "https://www.nhis.or.kr",
        "legal_basis": ["국민건강보험법 제6조"],
        "required_documents": ["전입신고 완료 후 자동 처리 (별도 서류 불필요)"],
        "application_channel": ["online", "call"],
        "contact": "국민건강보험공단 고객센터 1577-1000",
        "target_region": "all",
        "tags": ["이사", "건강보험", "주소변경"],
        "eligibility_summary": "전입신고 완료 후 자동 반영되는 경우가 많습니다.",
        "processing_days": "1~3 영업일",
        "fee": "무료",
    },
    "SVC003": {
        "service_id": "SVC003",
        "service_name": "차량 주소 변경 (자동차등록증 재발급)",
        "route": "gov24",
        "main_url": "https://www.gov.kr/portal/service/serviceInfo/PTR000050045",
        "legal_basis": ["자동차관리법 제11조"],
        "required_documents": ["자동차등록증", "신분증", "전입신고 확인서"],
        "application_channel": ["online", "visit"],
        "contact": "차량등록사업소",
        "target_region": "all",
        "tags": ["이사", "차량", "자동차", "주소변경"],
        "eligibility_summary": "차량 소유자가 주소를 변경한 경우 신고 의무가 있습니다.",
        "processing_days": "즉시 ~ 3일",
        "fee": "재발급 수수료 있음",
    },
    "SVC004": {
        "service_id": "SVC004",
        "service_name": "초등학교 전학 신청",
        "route": "local_gov",
        "main_url": "https://www.schoolinfo.go.kr",
        "legal_basis": ["초중등교육법 제21조"],
        "required_documents": ["전입신고 확인서", "재학증명서", "학생건강기록부"],
        "application_channel": ["visit"],
        "contact": "전입지 초등학교 교무실",
        "target_region": "all",
        "tags": ["이사", "전학", "초등학교", "자녀"],
        "eligibility_summary": "초등학생 자녀가 있는 경우 전입지 관할 학교에 전학 신청이 필요합니다.",
        "processing_days": "1~3일",
        "fee": "무료",
    },
    "SVC005": {
        "service_id": "SVC005",
        "service_name": "생활폐기물 처리 스티커 신청",
        "route": "local_gov",
        "main_url": "https://www.gov.kr",
        "legal_basis": ["폐기물관리법 제14조"],
        "required_documents": ["별도 서류 불필요"],
        "application_channel": ["online", "visit", "call"],
        "contact": "전입지 구청 환경과",
        "target_region": "all",
        "tags": ["이사", "폐기물", "대형폐기물", "스티커"],
        "eligibility_summary": "이사 시 발생하는 대형 폐기물 처리를 위해 지자체 수거 서비스를 신청할 수 있습니다.",
        "processing_days": "신청 후 2~7일",
        "fee": "품목별 수수료",
    },
    "SVC006": {
        "service_id": "SVC006",
        "service_name": "어린이집 입소 신청",
        "route": "gov24",
        "main_url": "https://www.childcare.go.kr",
        "legal_basis": ["영유아보육법 제27조"],
        "required_documents": ["주민등록등본", "신분증"],
        "application_channel": ["online"],
        "contact": "임신육아종합포털 아이사랑 1566-3232",
        "target_region": "all",
        "tags": ["이사", "보육", "어린이집", "자녀"],
        "eligibility_summary": "만 0~5세 영유아 자녀가 있는 경우 아이사랑 포털에서 대기 신청 가능합니다.",
        "processing_days": "대기 순번에 따라 상이",
        "fee": "소득분위별 상이",
    },
}
